lab_1/urls.py
from django.urls import path
from .views import index, friend_list

urlpatterns = [
    path('', index, name='index'),
    path('friends/', friend_list, name='friends')
    
]

lab_2/urls.py
from django.urls import path
from .views import index, xml, json
urlpatterns = [
    path('', index, name='index'),
    path('xml', xml, name='xml'),
    path('json', json, name='json')
]   

lab_3/urls.py
from django.urls import path
from .views import index, add_friend
urlpatterns = [
    path('', index, name='index'),
    path('add', add_friend, name="add")
]   

lab_4/urls.py
from django.urls import path
from .views import index, add_note, note_list
urlpatterns = [
    path('', index, name='index'),
    path('add-note', add_note, name='add-note'),
    path('note-list', note_list, name='note-list')
]   

praktikum/urls.py
from django.urls import path, re_path, include
from django.contrib import admin
import lab_1.urls as lab_1
import lab_2.urls as lab_2
import lab_3.urls as lab_3
import lab_4.urls as lab_4
from lab_1.views import index as index_lab1

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lab-1/', include('lab_1.urls')),
    path('lab-2/', include('lab_2.urls')),
    path('lab-3/', include('lab_3.urls')),
    path('lab-4/', include('lab_4.urls')),
    re_path(r'^$', index_lab1, name='index')
]

lab_1/models.py
from django.db import models
from datetime import datetime, date



class Friend(models.Model):
    name = models.CharField(max_length=30,default= " ")
    npm = models.CharField(max_length=10, default=" ")
    DOB = models.DateField(default=date.today)

lab_2/models.py
from django.db import models

class Note(models.Model):
    recipient = models.CharField(max_length=30, default=" ")
    sender = models.CharField(max_length=30, default=" ")
    title = models.CharField(max_length=30, default=" ")
    message = models.TextField(max_length=500, default=" ")

lab_3/models.py
from django.db import models

# Create your models here.

lab_4/models.py
from django.db import models

# Create your models here.

lab_3/forms.py
from django import forms
from lab_1.models import Friend

class FriendForm(forms.ModelForm):
    class Meta:
        model = Friend
        fields = ['name', 'npm', 'DOB']

lab_4/forms.py
from django import forms
from django.forms.widgets import TextInput, Textarea
from lab_2.models import Note

class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ["recipient", "sender", "title", "message"]
        widgets = {"recipient": TextInput(attrs={'placeholder': 'Recipient name'}),
            "sender": TextInput(attrs={'placeholder': 'Sender name'}),
            "title": TextInput(attrs={'placeholder': 'Title of your message'}),
            "message": Textarea(attrs={'placeholder': "Enter your message"}),}

lab_1/views.py
from django.shortcuts import render
from datetime import datetime, date
from .models import Friend

mhs_name = 'Figo Athallah'  
curr_year = int(datetime.now().strftime("%Y"))
birth_date = date(2002, 6, 8)  
npm = '2006535571' 


def index(request):
    response = {'name': mhs_name,
                'age': calculate_age(birth_date.year),
                'npm': npm}
    return render(request, 'index_lab1.html', response)


def calculate_age(birth_year):
    return curr_year - birth_year if birth_year <= curr_year else 0


def friend_list(request):
    friends = Friend.objects.all().values()
    response = {'friends': friends}
    return render(request, 'friend_list_lab1.html', response)

lab_2/views.py
from django.shortcuts import render
from django.http.response import HttpResponse
from django.core import serializers
from .models import Note

def index(request):
    notes = Note.objects.all().values()
    response = {"notes": notes}
    return render(request, 'lab2.html', response)

def xml(request):
    data = serializers.serialize('xml', Note.objects.all())
    return HttpResponse(data, content_type="application/xml")

def json(request):
    data = serializers.serialize('json', Note.objects.all())
    return HttpResponse(data, content_type="application/json")

lab_3/views.py
from django.http.response import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from lab_1.models import Friend
from .forms import FriendForm

@login_required(login_url='/admin/login')
def index(request):
    friends = Friend.objects.all().values()
    response = {'friends': friends}
    return render(request, 'lab3_index.html', response)

@login_required(login_url='/admin/login')
def add_friend(request):
    if request.method == "POST":
        form = FriendForm(request.POST or None)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect("/lab-3")

    else:
        form = FriendForm()

    response = {"form": form}
    return render(request, 'lab3_form.html', response)
    

lab_4/views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from lab_2.models import Note
from .forms import NoteForm


def index(request):
    notes = Note.objects.all().values()
    response = {"notes": notes}
    return render(request, 'lab4_index.html', response)

def add_note(request):
    if request.method == "POST":
        form = NoteForm(request.POST or None)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect("/lab-4")

    else:
        form = NoteForm()

    response = {"form": form}
    return render(request, 'lab4_form.html', response)

def note_list(request):
    notes = Note.objects.all().values()
    response = {"notes": notes}
    return render(request, 'lab4_note_list.html', response)

lab_1/templates/friend_list_lab1.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Friend List</title>
  </head>
  <body>
    <table>
      <tr>
        <th>name</th>
        <th>npm</th>
        <th>DOB</th>
      </tr>
      {% for friend in friends %}   
      <tr>
        <td>{{ friend.name }}</td>
        <td>{{ friend.npm }}</td> 
        <td>{{ friend.DOB }}</td>
      </tr>
      {% endfor %}
    </table>
  </body>
</html>

lab_1/templates/index_lab1.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>{{ name }}</title>
  </head>
  <body>
    <h1>Hello my name is {{ name }}</h1>
    <article>NPM : {{ npm }}</article>
    <article>I am {{ age }} years old</article>
  </body>
</html>

lab_2/templates/lab2.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>My Notes</title>
    <style>
    table, th, td {
      border: 1px solid black;
      border-collapse: collapse;
    }
  </style>
  </head>
  <body>
    <table>
      <tr>
        <th>To</th>
        <th>From</th>
        <th>Title</th>
        <th>Message</th>
      </tr>
      {% for note in notes %}   
      <tr>
        <td>{{ note.recipient }}</td>
        <td>{{ note.sender }}</td> 
        <td>{{ note.title }}</td>
        <td>{{ note.message }}</td>
      </tr>
      {% endfor %}
    </table>
  </body>
</html>

lab_3/templates/lab3_form.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Friend Form</title>
  </head>
  <body>
    <form action=""
    method=POST>
        {% csrf_token %}
        
        {{ form }}
        <input type="Submit" value="Submit">
    </form>
  </body>
</html>

lab_3/templates/lab3_index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Friend List</title>
  </head>
  <body>
    <table>
    <style>
    table, th, td {
        border: 1px solid black;
        border-collapse: collapse;
    }
    </style>
      <tr>
        <th>name</th>
        <th>npm</th>
        <th>DOB</th>
      </tr>
      {% for friend in friends %}   
      <tr>
        <td>{{ friend.name }}</td>
        <td>{{ friend.npm }}</td> 
        <td>{{ friend.DOB }}</td>
      </tr>
      {% endfor %}
    </table>
  </body>
</html>

lab_4/templates/lab4_form.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Note Form</title>
  </head>
  <style>
    body {background-color: #fffae8;}

    .topnav {
      background-color: #fddb45;
      background-image: linear-gradient(#ff961d, #fddb45);
      overflow: hidden;

    }

    .topnav a {
      float: left;
      color: #000000;
      text-align: center;
      padding: 14px 16px;
      text-decoration: none;
      font-family: Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif;
      font-size: 16px;
    }

    .topnav a:active {
        background-color: #ffe986;
    }


    input[type=text]:focus {
        border: 3px solid #0c0a0a;
    }   

    label {
        width: 80px;
        display: inline-block;
        font-family:'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif
    }

    #id_title {
        width: 200px;
    }

  </style>
  <body>
    <div class="topnav">
      <a href="/lab-4">Home</a>
      <a class="active" href="add-note">Add Note</a>
      <a href="note-list">Note List</a>
    </div>
    <form action=""
    method=POST>
    <table>
        {% csrf_token %}
        
        {{ form }}
    </table>
        <input type="Submit" value="Submit" style="width: 100px; margin-left:200px">
    </form>
  </body>
</html>

lab_4/templates/lab4_index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>My Notes</title>
    <style>
    
    body {background-color: #fffae8;}

    .topnav {
      background-color: #fddb45;
      background-image: linear-gradient(#ff961d, #fddb45);
      overflow: hidden;

    }

    .topnav a {
      float: left;
      color: #000000;
      text-align: center;
      padding: 14px 16px;
      text-decoration: none;
      font-family: Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif;
      font-size: 16px;
    }

    .topnav a:active {
        background-color: #ffe986;
    }


    table, th, td {
      border: 2px solid black;
      border-collapse: collapse;
    }
  
    table {
      font-size: 1rem;
      font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif
    }
    td {
      text-align: center;
    }

    th {
      background-color: #ff961d;
    }

    tr:nth-child(odd) {background-color: #fbffd5;}

    tr:nth-child(even) {background-color: #fffda0}

    tr:hover {background-color: #b7b99e;}
    
  </style>
  </head>
  <body>
    <div class="topnav">
      <a class="active" href="/lab-4">Home</a>
      <a href="add-note">Add Note</a>
      <a href="note-list">Note List</a>
    </div>
    <table>
      <tr>
        <th>To</th>
        <th>From</th>
        <th>Title</th>
        <th>Message</th>
      </tr>
      {% for note in notes %}   
      <tr>
        <td>{{ note.recipient }}</td>
        <td>{{ note.sender }}</td> 
        <td>{{ note.title }}</td>
        <td style= "width:400px;">{{ note.message }}</td>
      </tr>
      {% endfor %}
    </table>
  </body>
</html>

lab_4/templates/lab4_note_list.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Note List</title>
    <style>

    html {
        font-size: 15px;
    }

    body {
        background-color: #fffae8;
    }

    .topnav {
      background-color: #fddb45;
      background-image: linear-gradient(#ff961d, #fddb45);
      overflow: hidden;

    }

    .topnav a {
      float: left;
      color: #000000;
      text-align: center;
      padding: 14px 16px;
      text-decoration: none;
      font-family: Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif;
      font-size: 16px;
    }

    .topnav a:active {
        background-color: #ffe986;
    }

    .card { 
        box-shadow: 0 4px 8px 0 rgba(0, 0, 4, 0.9);
        background-color: #fffb28;
        padding: 16px;
        margin-bottom: 16px;
    }

    .row {
        float: left;
        padding: 0 10px;
    }

    .column {
        float: left;
        padding: 0 20px;
    }


    .container {
        line-height: 20px;
    }

</style>
  </head>
  <body>
    <div class="topnav">
        <a href="/lab-4">Home</a>
        <a href="add-note">Add Note</a>
        <a class="active" href="note-list">Note List</a>
      </div>
   <div class="row">
    {% for note in notes %}  
    <div class="column">
    <div class="card">
      <div class="container">
        <h1>To: {{note.recipient}}</h1>       
        <h2>From: {{note.sender}}</h2>
        <h3>Title: {{note.title}}</h3>
        <p>{{note.message}}</p>
      </div>
    </div>
    </div>
    {% endfor %}
   </div>
  </body>
</html>